---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:year ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge


### content configuration ###
title:       "ExpandoDB"
keywords:    "JSON, document database, Lucene, search, full-text search, Lucene index, information retrieval, REST, microservice, SQLite"
description: "A JSON document database with super-fast Lucene search"
source_link: "https://github.com/cris-almodovar/expando-db"
favicon:     "img/expando-db.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: "UA-75633558-1"  


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'  

kramdown:
  auto_ids:  false

