
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0133:Parameter name differs in base declaration", Justification = "<Pending>", Scope = "member", Target = "~M:ExpandoDB.Search.LuceneHighlighter.HighlighterQueryParser.GetBooleanQuery(java.util.List,System.Boolean)~FlexLucene.Search.Query")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0133:Parameter name differs in base declaration", Justification = "<Pending>", Scope = "member", Target = "~M:ExpandoDB.Search.LuceneHighlighter.HighlighterQueryParser.GetWildcardQuery(System.String,System.String)~FlexLucene.Search.Query")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0133:Parameter name differs in base declaration", Justification = "<Pending>", Scope = "member", Target = "~M:ExpandoDB.Search.LuceneHighlighter.HighlighterQueryParser.GetBooleanQuery(java.util.List)~FlexLucene.Search.Query")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0133:Parameter name differs in base declaration", Justification = "<Pending>", Scope = "member", Target = "~M:ExpandoDB.Search.LuceneHighlighter.HighlighterQueryParser.GetRegexpQuery(System.String,System.String)~FlexLucene.Search.Query")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0133:Parameter name differs in base declaration", Justification = "<Pending>", Scope = "member", Target = "~M:ExpandoDB.Search.LuceneHighlighter.HighlighterQueryParser.GetPrefixQuery(System.String,System.String)~FlexLucene.Search.Query")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0133:Parameter name differs in base declaration", Justification = "<Pending>", Scope = "member", Target = "~M:ExpandoDB.Search.LuceneHighlighter.HighlighterQueryParser.GetFuzzyQuery(System.String,System.String,System.Single)~FlexLucene.Search.Query")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0133:Parameter name differs in base declaration", Justification = "<Pending>", Scope = "member", Target = "~M:ExpandoDB.Search.LuceneHighlighter.HighlighterQueryParser.GetRangeQuery(System.String,System.String,System.String,System.Boolean,System.Boolean)~FlexLucene.Search.Query")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0133:Parameter name differs in base declaration", Justification = "<Pending>", Scope = "member", Target = "~M:ExpandoDB.Search.LuceneHighlighter.HighlighterQueryParser.GetFieldQuery(System.String,System.String,System.Int32)~FlexLucene.Search.Query")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0133:Parameter name differs in base declaration", Justification = "<Pending>", Scope = "member", Target = "~M:ExpandoDB.Search.LuceneHighlighter.HighlighterQueryParser.GetFieldQuery(System.String,System.String,System.Boolean)~FlexLucene.Search.Query")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0133:Parameter name differs in base declaration", Justification = "<Pending>", Scope = "member", Target = "~M:ExpandoDB.Search.CompositeAnalyzer.GetWrappedAnalyzer(System.String)~FlexLucene.Analysis.Analyzer")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0133:Parameter name differs in base declaration", Justification = "<Pending>", Scope = "member", Target = "~M:ExpandoDB.Search.FullTextAnalyzer.CreateComponents(System.String)~FlexLucene.Analysis.AnalyzerTokenStreamComponents")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0133:Parameter name differs in base declaration", Justification = "<Pending>", Scope = "member", Target = "~M:ExpandoDB.Search.LuceneQueryParser.GetRangeQuery(System.String,System.String,System.String,System.Boolean,System.Boolean)~FlexLucene.Search.Query")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0133:Parameter name differs in base declaration", Justification = "<Pending>", Scope = "member", Target = "~M:ExpandoDB.Search.LuceneQueryParser.GetFieldQuery(System.String,System.String,System.Boolean)~FlexLucene.Search.Query")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0133:Parameter name differs in base declaration", Justification = "<Pending>", Scope = "member", Target = "~M:ExpandoDB.Search.LuceneQueryParser.GetFuzzyQuery(System.String,System.String,System.Single)~FlexLucene.Search.Query")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0133:Parameter name differs in base declaration", Justification = "<Pending>", Scope = "member", Target = "~M:ExpandoDB.Search.LuceneQueryParser.GetPrefixQuery(System.String,System.String)~FlexLucene.Search.Query")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0133:Parameter name differs in base declaration", Justification = "<Pending>", Scope = "member", Target = "~M:ExpandoDB.Search.LuceneQueryParser.GetRegexpQuery(System.String,System.String)~FlexLucene.Search.Query")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0133:Parameter name differs in base declaration", Justification = "<Pending>", Scope = "member", Target = "~M:ExpandoDB.Search.LuceneQueryParser.GetWildcardQuery(System.String,System.String)~FlexLucene.Search.Query")]

